#!/usr/bin/env bash

Prog=$(basename "$0")

read -rd '' Usage <<END
Usage:
  $Prog cake --buttercream <chocolate|vanilla> [temperature]          make a cake
END

# commands are capitalized
##########################

# Cake mixes and bakes a delicious cake.
Cake() {
  Flavor=${1:-}
  Temperature=${2:-${Defaults[temperature]}}

  [[ $Flavor != "" ]] || { echo "Error: missing flavor."; exit 2; }

  announce mix $Flavor

  announce bake $Temperature

  (( Buttercream )) && echo "mmm, buttercream added"
}

# non-commands
##############

# mix mixes the batter.
mix() {
  local flavor=$1

  echo "mixing $flavor batter..."

  sleep 2

  echo "mixed!"
}

# bake bakes the cake.
bake() {
  local temperature=$1

  echo "baking at $temperature degrees..."

  sleep 1

  echo "baked!"
}

# setup
#######

MkLib=$MKDIR/mk.bash    # you must hardcode or provide MKDIR

source "$MkLib" 2>/dev/null || { echo "$MkLib not found. Is MKDIR set?"; exit 2; }

Args=( "$@" ); processArgs; set -- "${Args[@]}"; unset -v Args   # parse standard flags

declare -A Defaults=(
  [temperature]=350
)

Buttercream=0

set -eu

case ${2:-} in
  --buttercream ) Buttercream=1; set -- "$1" "${@:3}";;   # remove flag
esac

main "$@"
