#!/usr/bin/env bash

Prog=$(basename "$0")   # match what the user called
Version=0.2

read -rd '' Usage_ <<END
Usage:

  $Prog [OPTIONS] [--] git-update DIR [DIR...]

  git-update    if the upstream branch has made progress, git-update rebases the current
                branch on its upstream.

  Options:

    -h | --help     show this message and exit
    -v | --version  show the program version and exit
    -x | --trace    enable debug tracing
END

## commands

cmd.git-update() {
  (( $# > 0 )) || mk.Fatal 'directory required' 2
  mk.Stream "$@" |
    mk.KeepIf isGitRepo |
    mk.Each rebaseIfUpstreamHasProgressed
}

cmd.urma() (  # subshell for cd
  [[ -e ~/fa-token.txt ]] || mk.Fatal 'missing fontawesome token file: ~/fa-token.txt'
  mk.Each mk.Cue <<'  END'
    git clone git@stash.digi.com:idigi/urma-next ~/urma-next
    cd ~/urma-next/urma-next/scripts
    git checkout -b local origin/tlilley/local
  END
  export FONTAWESOME_PACKAGE_TOKEN=$(<~/fa-token.txt)
  mk.Cue ./urma install

)

## helpers

# isGitRepo returns whether its argument contains a .git directory.
isGitRepo() { [[ -d "$1"/.git ]]; }

# isMergeBaseOf returns whether ref2 is the merge-base of ref and ref2.
isMergeBaseOf() {
  local ref=$1 ref2=$2 mergeBase
  mergeBase=$(git merge-base $ref $ref2)
  [[ $mergeBase == "$ref2" ]]
}

# rebaseIfUpstreamHasProgressed rebases a repo if its upstream branch has been updated.
# It runs in a subshell so it can change directory without affecting the caller.
rebaseIfUpstreamHasProgressed() (
  local dir=$1

  mk.Cue cd $dir
  mk.Cue git fetch

  local ref=$(git rev-parse HEAD)
  local upstreamRef=$(git rev-parse @{upstream})
  isMergeBaseOf $ref $upstreamRef || mk.Cue git rebase $upstreamRef

  echo
)

## globals

## boilerplate

source ~/.local/lib/mk.bash 2>/dev/null || { echo 'fatal: mk.bash not found' >&2; exit 1; }

# enable safe expansion
IFS=$'\n'
set -o noglob

mk.SetProg $Prog
mk.SetUsage "$Usage_"
mk.SetVersion $Version

return 2>/dev/null    # stop if sourced, for interactive debugging
mk.HandleOptions "$@" # standard options
mk.Main "${@:$?}"      # showtime
